avoid installing unnecessary deps in CI

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -16,9 +16,9 @@ cd "$(dirname "$0")/.."
 
 echo "==> Resolving dependencies..."
 
-hash brew 2>/dev/null && {
-  brew bundle check >/dev/null 2>&1  || {
-    echo "==> Installing Homebrew dependencies..."
-    brew bundle --no-lock
+command -v brew >/dev/null && {
+  brew bundle check --verbose --file=Brewfile  || {
+    echo "==> Installing missing dependencies via Homebrew..."
+    brew bundle install --verbose --file=Brewfile --no-lock
   }
 }
